// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGY_zC7vCQkRVNDBua8-sWR_jrvzy6mA0',
    appId: '1:1097520684101:web:76d750e558983b194cd72c',
    messagingSenderId: '1097520684101',
    projectId: 'zill-ed319',
    authDomain: 'zill-ed319.firebaseapp.com',
    storageBucket: 'zill-ed319.firebasestorage.app',
    measurementId: 'G-1VMHHSYMRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfb0Q87xJSlAFItXQeHtuc28MH-8qRtVc',
    appId: '1:1097520684101:android:c7f7b2c4a663e1294cd72c',
    messagingSenderId: '1097520684101',
    projectId: 'zill-ed319',
    storageBucket: 'zill-ed319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2n8oVstR-3BzQEZivZcRavYyQ3uK8hts',
    appId: '1:1097520684101:ios:e5a671c9435fd4a44cd72c',
    messagingSenderId: '1097520684101',
    projectId: 'zill-ed319',
    storageBucket: 'zill-ed319.firebasestorage.app',
    iosBundleId: 'com.example.zillSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2n8oVstR-3BzQEZivZcRavYyQ3uK8hts',
    appId: '1:1097520684101:ios:e5a671c9435fd4a44cd72c',
    messagingSenderId: '1097520684101',
    projectId: 'zill-ed319',
    storageBucket: 'zill-ed319.firebasestorage.app',
    iosBundleId: 'com.example.zillSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGY_zC7vCQkRVNDBua8-sWR_jrvzy6mA0',
    appId: '1:1097520684101:web:731d70fbf66043fd4cd72c',
    messagingSenderId: '1097520684101',
    projectId: 'zill-ed319',
    authDomain: 'zill-ed319.firebaseapp.com',
    storageBucket: 'zill-ed319.firebasestorage.app',
    measurementId: 'G-RTTH55RB58',
  );
}
